[package]
name = "chipioindustries/llama"
description = "Luau Library for Immutable Data"
version = "1.3.2"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["docs", "wally.exe", "tests", "test", ".github"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
