[package]
name = "teamswordphin/rnginventorysystem"
description = "RNG Inventory"
version = "1.0.0"
authors = ["TeamSwordphin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
ProfileService = "brittonfischer/profileservice@2.1.5"
ReplicaService = "brittonfischer/replicaservice@0.1.0"
Freeze = "duckarmor/freeze@0.1.4"
RandomSelection = "chipioindustries/random-selection@1.0.1"
Janitor = "howmanysmall/janitor@1.16.0"