return {
	[1] = { Name = "Common", Color = Color3.fromRGB(235, 235, 235) },
	[2] = { Name = "Uncommon", Color = Color3.fromRGB(132, 211, 138) },
	[3] = { Name = "Rare", Color = Color3.fromRGB(75, 92, 168) },
	[4] = { Name = "Epic", Color = Color3.fromRGB(110, 51, 117) },
	[5] = { Name = "Legendary", Color = Color3.fromRGB(247, 237, 101) },
	[6] = { Name = "Mythic", Color = Color3.fromRGB(255, 98, 98) },
}
